# Generated by Django 6.0.5 on 2026-05-22 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=80, verbose_name='Квалификация')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код направления')),
                ('name', models.CharField(max_length=180, verbose_name='Направление')),
                ('profile', models.CharField(max_length=220, verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'направление подготовки',
                'verbose_name_plural': 'направления подготовки',
                'ordering': ['qualification', 'code', 'name', 'profile'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=180, verbose_name='ФИО')),
                ('position', models.CharField(choices=[('Заведующий кафедрой', 'Заведующий кафедрой'), ('Профессор', 'Профессор'), ('Доцент', 'Доцент'), ('Старший преподаватель', 'Старший преподаватель')], max_length=80, verbose_name='Должность')),
                ('academic_title', models.CharField(blank=True, max_length=120, verbose_name='Ученое звание')),
                ('photo_url', models.URLField(blank=True, verbose_name='URL фотографии')),
                ('bio', models.TextField(blank=True, verbose_name='Краткая информация')),
                ('directions', models.ManyToManyField(blank=True, to='core.direction', verbose_name='Направления подготовки')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
                'ordering': ['full_name'],
            },
        ),
    ]
