# Generated by Django 6.0.5 on 2026-05-22 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название дисциплины')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Код дисциплины')),
                ('hours', models.PositiveIntegerField(default=72, verbose_name='Часов')),
                ('semester', models.PositiveSmallIntegerField(default=1, verbose_name='Семестр')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='core.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'дисциплина',
                'verbose_name_plural': 'дисциплины',
                'ordering': ['semester', 'name'],
            },
        ),
    ]
